### ISSUE TITLE
Unable to progress in Twilight Forest

### ISSUE THREAD

**Issue by MechanosG** [NillerMedDild/Enigmatica2#150]
**Issue Description**
Unable to complete "Time to Even the Scales" advancement.  The tower doesn't drop it's protection and I'm unable to continue.

**Modpack version (Do not use "latest")**
Enigmatica 2 - 1.51

**Logs**
N/A

**Screenshots**
![2018-11-04_14 17 46](https://user-images.githubusercontent.com/4360512/47970638-15502180-e03d-11e8-8c4f-5565d9f6ffa5.jpg)

**Additional context**
I've killed the Naga 3 times now.  I've tried using different weapons.  First I used a laser, then I used a scythe, then I used a kama, all Tinker's weapons.  I've tried throwing the scales and trophy on the ground repeatedly and picking them back up.  I'm not wearing any items that affect item pickup, and just to be sure I unequipped everything then threw the naga stuff on the ground again.  I asked Reddit for advice, and they seem to think that the scales are the only thing I need to progress now.  I heard a rumor that the advancement is linked to raven feathers and the magic map, so I also created one of those.  Nothing seems to work, and the "Time to Even the Scales" advancement shows only 1/2 things completed, but some of the text is garbled, I assume due to something Better Advancements is doing.

Not sure if this is a bug or if I'm doing something wrong.  Any ideas?

**Comment by NillerMedDild** [comment]
I think you have to make the Magical Map prior to killing the Naga, do you mind trying that?

**Comment by MechanosG** [comment]
Heya.  Yep, I've made multiple maps.  I also posted on the Twilight Forest github https://github.com/TeamTwilight/twilightforest/issues/646 about the issue.  Apparently my Twilight Hunter advancement isn't triggering, and is a requirement before I can do the Naga and stuffs.  Could something in Enigmatica 2 be preventing the kill detection?  Maybe the extra damage from the Nutrition mod or something?

**Comment by NillerMedDild** [comment]
Not really no, the damage boost from Nutrition comes from the vanilla strength potion effect. Is the issue solved? :)

**Comment by MechanosG** [comment]
Nope, issue persists.  I can't get the Twilight Hunter advancement to trigger for whatever reason.  About 5 minutes ago I just ran all over Twilight Forest killing all the wildlife, both with a Tinker kama and barehanded.  Not sure why it isn't triggering.

**Comment by NillerMedDild** [comment]
I think you'll have to grant it to yourself with a command.

**Comment by NillerMedDild** [comment]
`/advancement grant playername only twilightforest:progress_naga` should do the trick.

**Comment by MechanosG** [comment]
I'm on a multiplayer server, so that's slightly difficult to do.  But I know the owner so I'll keep that in mind, thx.  I assume I'd use:
/advancement grant playername only twilightforest:twilight_hunter
to progress the prerequisite first?

**Comment by NillerMedDild** [comment]
Nope, the grant only command also grants prerequisites :)

**Comment by PaternoX** [comment]
i have this issue, on enigmatica 2 expert. killed naga several times, still cant access lich tower. could it be because i already got the advancement for fiery tolls before entering the twilight forest?

**Comment by NillerMedDild** [comment]
Could be, I suggest you try the command supplied above.

**Comment by MechanosG** [comment]
Heya.  Been a while.  Just in case anyone's interested, the above command did unlock the achievements, but never did let me progress further.  I can't remember the details, as it's been like over a year.  But I do remember just giving up on Twilight Forest, mainly since I didn't have access to my character on the server to try and restart whatever broke.  To this day I still dunno for sure what happened.

**Comment by Cycov** [comment]
For anyone still experiencing this issue I found that the bug can be solved by using `/gamerule tfEnforcedProgression false`. You have to follow progression as intended carefully though, as the mod is designed around this system.

The other way was decompiling and recompiling the source code of the .jar and removing achievement check for Lich tower. Did it on my machine but it needs to be taken up with the mod author.

**Comment by mhelvens** [comment]
I'm experiencing the same issue. If it helps, here's a stacktrace that I believe happened right around killing the Naga the first time:

```
[12:03:34] [Server thread/FATAL] [minecraft/IntegratedServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_265]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:179) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
	at net.minecraft.advancements.PlayerAdvancements.func_194220_a(PlayerAdvancements.java:360) ~[np.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_194027_a(NetHandlerPlayServer.java:447) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketSeenAdvancements.func_148833_a(SourceFile:50) ~[lu.class:?]
	at net.minecraft.network.play.client.CPacketSeenAdvancements.func_148833_a(SourceFile:11) ~[lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 3 more
[12:03:40] [Server thread/FATAL] [minecraft/IntegratedServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_265]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:179) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
	at net.minecraft.advancements.PlayerAdvancements.func_194220_a(PlayerAdvancements.java:360) ~[np.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_194027_a(NetHandlerPlayServer.java:447) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketSeenAdvancements.func_148833_a(SourceFile:50) ~[lu.class:?]
	at net.minecraft.network.play.client.CPacketSeenAdvancements.func_148833_a(SourceFile:11) ~[lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 3 more
```
It mentions advancements. Also, When I open up my advancements, I can't find a Twilight Forest tab at all. :-/

**Comment by NillerMedDild** [comment]
I'm afraid there's not much we can do :/ The bug has been reported multiple times, no fix at this time.

**Comment by ayyEve** [comment]
note to server users, if you change the gamerule the field will still be visible however the effects will be gone. the server needs to be restarted (or the client reconnected, haven;t confirmed) in order for the field to disappear.
