### ISSUE TITLE
crash report every time i craft Mekanism solar panels

### ISSUE THREAD

**Issue by Titanblade828** [NillerMedDild/Enigmatica2#218]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
every time i try shift clicking the recipe for crafting the solar panels from Mekanism my single player world crashes to desktop i have 10Gb of ram so i know its not that issue. loving the pack other than this issue thank you

**Modpack Version**
1.54 

**Additional Context**
Description: Rendering ingredient

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:126)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:62)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:31)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:156)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:98)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:96)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:160)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3493_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:164)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:126)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)

-- Ingredient being rendered --
Details:
	Ingredient Mod: Environmental Tech
	Ingredient Info: 1xtile.environmentaltech.solar_cont_3@0 environmentaltech:solar_cont_3
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:255)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:33)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:156)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:98)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:96)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:160)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3493_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:164)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: slimeknights.tconstruct.tools.common.client.GuiCraftingStation
	Mouse location: Scaled: (391, 142). Absolute: (1174, 588)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3

**Comment by Titanblade828** [comment]
okay thanks

**Comment by NillerMedDild** [comment]
You're welcome :)
