### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by MaxiSevTech** [NillerMedDild/Enigmatica2#26]
#### Crash Report

[pastebin/gist/etc link here]

**Comment by MaxiSevTech** [comment]
Time: 5/14/18 7:02 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: -100
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at shadows.toaster.ToastControl.keys(ToastControl.java:45)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2292_ToastControl_keys_KeyInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:564)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2015)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by NillerMedDild** [comment]
Closed due to lack of response.

**Comment by NillerMedDild** [comment]
Closed due to lack of response.
