### ISSUE TITLE
First time launch error

### ISSUE THREAD

**Issue by tinkster888** [NillerMedDild/Enigmatica2#515]
Having trouble launching the modpack for the first time all I get is this error:

Time: 7/8/19 5:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:628)
	at java.util.HashMap.put(HashMap.java:611)
	at net.minecraft.nbt.NBTTagCompound.func_74774_a(NBTTagCompound.java:91)
	at forestry.core.genetics.Genome.writeToNBT(Genome.java:244)
	at forestry.core.genetics.IndividualLiving.writeToNBT(IndividualLiving.java:48)
	at forestry.apiculture.genetics.Bee.writeToNBT(Bee.java:126)
	at forestry.apiculture.genetics.BeeRoot.getMemberStack(BeeRoot.java:149)
	at net.bdew.jeibees.misc.GeneticsHelper$.getItemFromTemplate(GeneticsHelper.scala:53)
	at net.bdew.jeibees.misc.GeneticsHelper$.getItemFromSpecies(GeneticsHelper.scala:59)
	at net.bdew.jeibees.recipes.mutation.MutationRecipe.<init>(MutationRecipe.scala:29)
	at net.bdew.jeibees.BeesJEIPlugin$$anonfun$register$2$$anonfun$1.apply(BeesJEIPlugin.scala:84)
	at net.bdew.jeibees.BeesJEIPlugin$$anonfun$register$2$$anonfun$1.apply(BeesJEIPlugin.scala:84)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.bdew.jeibees.BeesJEIPlugin$$anonfun$register$2.apply(BeesJEIPlugin.scala:84)
	at net.bdew.jeibees.BeesJEIPlugin$$anonfun$register$2.apply(BeesJEIPlugin.scala:79)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.immutable.Map$Map4.foreach(Map.scala:188)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at net.bdew.jeibees.BeesJEIPlugin.register(BeesJEIPlugin.scala:79)
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:202)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by NillerMedDild** [comment]
You need to allocate more RAM, 7GB would be great if possible,
