### ISSUE TITLE
Missing texture files

### ISSUE THREAD

**Issue by kols** [NillerMedDild/Enigmatica2#600]
**Modpack version**
Enigmatica2Server-1.75b
Downloaded from curseforge

**Issue**
Main menu graphics glitches, seems the modpack doesn't have the texture files packaged.

**Logs**
```
java.io.FileNotFoundException: modpack:textures/gui/button2.png
	at net.minecraft.client.resources.SimpleReloadableResourceManager.getResource(SimpleReloadableResourceManager.java:69) ~[cev.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.loadTexture(SimpleTexture.java:40) ~[cdm.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:90) [cdr.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:60) [cdr.class:?]
	at lumien.custommainmenu.lib.textures.TextureResourceLocation.bind(TextureResourceLocation.java:16) [TextureResourceLocation.class:?]
	at lumien.custommainmenu.gui.GuiCustomButton.drawButton(GuiCustomButton.java:85) [GuiCustomButton.class:?]
	at lumien.custommainmenu.gui.GuiCustom.drawScreen(GuiCustom.java:434) [GuiCustom.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by kols** [comment]
Figured out they are in client package...
Closing.
